### ISSUE TITLE
Installation fails database migration.

### ISSUE THREAD

**Issue by conca** [apioo/fusio#365]
This used to work couple days ago.

When getting Fusio from composer (`composer create-project fusio/fusio`), `install.php` doesn't work anymore. It is populating the `.env` file correctly, but getting a `500` error when performing database migrations. Unfortunately the response is empty, so I don't have more details.

I also tried to do it with `php bin/fusio install` but the command is not updating the database either.

<img width="1440" alt="Screen Shot 2021-02-07 at 9 22 30 AM" src="https://user-images.githubusercontent.com/3878229/107154645-e9f9c280-6928-11eb-94c2-d64967b571b6.png">

**Comment by chriskapp** [comment]
Hi, ok it looks like this occurred during the fix of https://github.com/apioo/fusio/issues/362 we will take a look at it to find a secure way to escape those values. To fix this locally you could remove the `preg_quote` at https://github.com/apioo/fusio/blob/master/public/install.php#L206

**Comment by chriskapp** [comment]
This should be solved with the latest release

**Comment by panorigin** [comment]
Is this bug fixed? I tried just now but still failed even though I clone the latest repository.
