### ISSUE TITLE
Backend app need paging or scroll

### ISSUE THREAD

**Issue by zaniar** [apioo/fusio#67]
I have many actions. I can not access some of the actions because they are not displayed.
This issue also happened to route, and scope. It may happened on somewhere else.

Currently, the only way to access those hidden items is using search.

Ideally, there should be pagination or scroll.

**Comment by k42b3** [comment]
Hi, yes these panels should have a pagination. In previous versions of the backend app there was a problem that the pagination was not displayed after we have updated the angular UI bootstrap but this should be fixed in the latest version. Do you use the latest version of the backend app? Otherwise please [download](https://www.fusio-project.org/download) it and replace the files in `public/fusio` and test whether this fixes the problem.

**Comment by zaniar** [comment]
@k42b3 I installed the the new version and the problem is gone 👍

**Comment by zaniar** [comment]
The problem is gone on Route, but it is still exist on Update popup when I editing Scope.

**Comment by k42b3** [comment]
Ok this is indeed a bug at the scope edit panel that we dont show all available routes. Since this is also a form we should simply display all available routes without pagination.

**Comment by k42b3** [comment]
So I have found the problem and commited a fix https://github.com/apioo/fusio-impl/commit/f6e8e2e0feb965b901d13ff2ef1b9f7849f5cf12
The problem was that the count parameter was not correctly handled so the API always returned 16 entries.
